### ISSUE TITLE
编译报错：Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES OPENSCENEGRAPH_INCLUDE_DIR OSGDB_FOUND OSGUTIL_FOUND OSG_FOUND OPENTHREADS_FOUND) (Required is at least version "2.0.0")

### ISSUE THREAD

**Issue by lidongzhuo** [ProjSEED/To3mx#2]
C:\Users\user\Desktop\To3mx-master>cmake .
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test _cpp_latest_flag_supported
-- Performing Test _cpp_latest_flag_supported - Success
-- Could NOT find osgDB (missing: OSGDB_LIBRARY OSGDB_INCLUDE_DIR)
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY OSGUTIL_INCLUDE_DIR)
-- Could NOT find osg (missing: OSG_LIBRARY OSG_INCLUDE_DIR)
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY OPENTHREADS_INCLUDE_DIR)
CMake Error at D:/Software/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES
  OPENSCENEGRAPH_INCLUDE_DIR OSGDB_FOUND OSGUTIL_FOUND OSG_FOUND
  OPENTHREADS_FOUND) (Required is at least version "2.0.0")
Call Stack (most recent call first):
  D:/Software/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  D:/Software/cmake/share/cmake-3.18/Modules/FindOpenSceneGraph.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/user/Desktop/To3mx-master/CMakeFiles/CMakeOutput.log".

C:\Users\user\Desktop\To3mx-master>

**Comment by GitGaoXing** [comment]
CMake里配置一下OSG路径啊

**Comment by lidongzhuo** [comment]
能发一个编译好的exe文件吗？谢谢。

**Comment by GitGaoXing** [comment]
https://github.com/ProjSEED/To3mx/releases/tag/v1.0
